Repository openSW-team3/eduGit-Github, pull requests merged in 2022-08, with the labels that each got.

#6 [feat]: 저장소 Issues 메뉴의 Labels 템플릿 추가 (#5)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/help.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ FEAT

#8 [feat]: 저장소 Issues 메뉴의 Labels 템플릿 수정 (#7)
  .github/ISSUE_TEMPLATE/help.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: 🛠 FIX

#10 [fix]: 홈페이지 요소 수정 (#9)
  src/data.js
  src/data/accessibility.js
  src/data/algorithms.js
  src/data/architecture-and-paradigmes.js
  src/data/block_1_Collection.js
  src/data/block_2_Collection.js
  src/data/block_3_Collection.js
  src/data/block_4_Collection.js
  src/data/block_5_Collection.js
  src/data/block_6_Collection.js
  src/data/build-tools.js
  src/data/databases.js
  src/data/design-and-ux.js
  src/data/frameworks-and-libraries.js
  src/data/fundamentals.js
  src/data/modern.js
  src/data/pwa.js
  src/data/team-collaboration.js
  src/data/testing.js
  src/data/web-components.js
  src/molecules/area.js
  src/molecules/collection.js
Labels: 🛠 FIX, 💄 UI/UX

#16 [fix]: 홈페이지 블록 요소 수정 (#14)
  src/data/block_1_Collection.js
  src/data/block_2_Collection.js
  src/data/block_3_Collection.js
  src/data/block_4_Collection.js
  src/data/block_5_Collection.js
  src/data/block_6_Collection.js
Labels: 🛠 FIX

#19 [fix]: README.md FAQ 수정 (#17)
  README.md
Labels: 🛠 FIX

#20 [fix]: git init 유닛 요소 설명 내용 수정 (#18)
  src/data/block_1_Collection.js
Labels: 🛠 FIX

#26 [fix]: (3. Branch와 Merge) 블록 내부의 유닛 데이터 수정 (#25)
  src/data/block_3_Collection.js
Labels: 🛠 FIX

#27 [fix]: (1.Git 프로젝트 생성하기, 가져오기) 블록 내부의 유닛 데이터 수정 (#23)
  src/data/block_1_Collection.js
Labels: 🛠 FIX

#29 [fix]: (4. Log) 블록 내부의 유닛 데이터 수정 (#28)
  src/data/block_4_Collection.js
Labels: 🛠 FIX

#32 [fix]: (5. 공유 & 업데이트) 블록 내부의 유닛 데이터 수정 (#24)
  src/data/block_5_Collection.js
Labels: 🛠 FIX

#31 [fix]: (2.Snapshot 스냅샷 다루기) 블록 내부의 유닛 데이터 수정 (#30)
  src/data/block_2_Collection.js
Labels: 🛠 FIX

#35 [fix]: README.md 링크 대제목 수정 (#34)
  README.md
Labels: 🛠 FIX

#37 [fix]: README.md 링크 소제목 수정 (#36)
  README.md
Labels: 🛠 FIX

#38 [fix]: (6. 임시 저장) 블록 내부의 유닛 데이터 수정 (#33)
  src/data/block_6_Collection.js
Labels: 🛠 FIX

#40 [fix]: 유닛 정보에 맞는 구글 및 유튜브 검색이 가능하도록 코드 수정 (#39)
  src/atoms/description.js
Labels: 🛠 FIX

#43 [fix]: README.md 각 block별 링크 수정 (#41)
  README.md
Labels: 🛠 FIX

#44 [fix]: git pull 유닛의 설명이 보이지 않는 문제 수정 (#42)
  src/data/block_5_Collection.js
Labels: 🐛 BUG, 🛠 FIX

#49 [fix] 홈페이지 블록 배치 관련 CSS 변경 (#48)
  src/app.js
Labels: 🛠 FIX, 💄 UI/UX

#51 [fix]: Open help 내용 수정 (#50)
  src/util/open-help.js
Labels: 🛠 FIX

#53 [fix]: README.md 각 block별 text 수정 (#52)
  README.md
Labels: 🛠 FIX

#57 [fix]: CONTRIBUTING.md 내용 수정 (#56)
  CONTRIBUTING.md
Labels: 🛠 FIX

#59 [fix]: README.md table of contents 수정 (#58)
  README.md
Labels: 🛠 FIX

#63 [fix]: 프로젝트 README.md 파일 내용 수정 (#62)
  README.md
Labels: 🛠 FIX

#61 [fix]: 홈페이지 헤더 내 특정 버튼 요소 제거 (#60)
  src/app.js
Labels: 🛠 FIX

#65 [fix]: CONTRIBUTING.md 파일 내용 수정 (#64)
  CONTRIBUTING.md
Labels: 🛠 FIX

#67 [fix]: CONTRIBUTING.md PR 규칙 관련 내용 수정 (#66)
  CONTRIBUTING.md
Labels: 🛠 FIX
